### ISSUE TITLE
workaround failing in more recent versions of docker

### ISSUE THREAD

**Issue by arashd** [boucher/criu-for-mac#5]
I've been trying to get the checkpoint/restore experimental feature of docker to work on a mac. 

After turning on the experimental feature, I see:

```
$ docker checkpoint create 53fc5dcc6fc9 checkpoint1
Error response from daemon: Cannot checkpoint container 53fc5dcc6fc9: runc did not terminate sucessfully: CRIU version check failed: exec: "criu": executable file not found in $PATH path= /var/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/53fc5dcc6fc9376f1cf067015750ce67cfbac1863a86b73593cc3dbab974223f/criu-dump.log: unknown
```

criu doesn't exist on the vm that docker for mac uses by default. I am pretty sure I need to install CRIU on the d4m linux vm. I attempted to use this approach (https://github.com/boucher/criu-for-mac), but realized it doesn’t work since docker for mac, in its newer versions, uses a `.iso` file built with Linuxkit for its vm, and the image has a read-only filesystem.

```
$ docker run --rm -it --privileged --pid=host boucher/criu-for-mac
sh: criu: not found
ERROR: Unable to lock database: Read-only file system
ERROR: Failed to open apk database: Read-only file system
```

The closest I could get was this [post](https://medium.com/@notsinge/making-your-own-linuxkit-with-docker-for-mac-5c1234170fb1), which attempts to pull out some of the missing pieces out of the existing docker for mac image: https://github.com/singe/linuxkit-for-mac.

Is there a better way of doing this that isn’t as brittle, and has someone made the above work?

Would appreciate any help.

**Comment by boucher** [comment]
I stopped following this a while ago, but from what I understand the read-only nature does make the approach in this repo stop working. There's a thread in the official for-mac repo that you might want to chime in on: https://github.com/docker/for-mac/issues/1059

**Comment by arashd** [comment]
Appreciate the quick response. Will do.
